export function getMonths(n: number) {
  const today = new Date()
  const months = []
  for (let i = 0; i < n; i++) {
    const month = today.getMonth()
    const year = today.getFullYear()
    const daysInMonth = new Date(year, month + 1, 0).getDate()
    const days = []
    for (let j = 1; j <= daysInMonth; j++) {
      days.push({
        date: new Date(year, month, j).toISOString().split('T')[0],
        dateIsoString: new Date(year, month, j).toISOString(),
        name: new Date(year, month, j).toLocaleString('default', {
          weekday: 'short',
        }),
        dayIndex: new Date(year, month, j).getDay(),
        day: j,
      })
    }
    months.push({
      year: year,
      monthIndex: month,
      offset: days[0].dayIndex,
      name: today.toLocaleString('default', { month: 'long' }),
      days,
    })
    today.setMonth(month + 1)
  }
  return months
}

export const months = [
  {
    year: 2024,
    monthIndex: 2,
    name: 'March',
    days: [
      {
        date: '2024-03-01',
        name: 'Fri',
        dayIndex: 5,
        day: 1,
      },
      {
        date: '2024-03-02',
        name: 'Sat',
        dayIndex: 6,
        day: 2,
      },
      {
        date: '2024-03-03',
        name: 'Sun',
        dayIndex: 0,
        day: 3,
      },
      {
        date: '2024-03-04',
        name: 'Mon',
        dayIndex: 1,
        day: 4,
      },
      {
        date: '2024-03-05',
        name: 'Tue',
        dayIndex: 2,
        day: 5,
      },
      {
        date: '2024-03-06',
        name: 'Wed',
        dayIndex: 3,
        day: 6,
      },
      {
        date: '2024-03-07',
        name: 'Thu',
        dayIndex: 4,
        day: 7,
      },
      {
        date: '2024-03-08',
        name: 'Fri',
        dayIndex: 5,
        day: 8,
      },
      {
        date: '2024-03-09',
        name: 'Sat',
        dayIndex: 6,
        day: 9,
      },
      {
        date: '2024-03-10',
        name: 'Sun',
        dayIndex: 0,
        day: 10,
      },
      {
        date: '2024-03-11',
        name: 'Mon',
        dayIndex: 1,
        day: 11,
      },
      {
        date: '2024-03-12',
        name: 'Tue',
        dayIndex: 2,
        day: 12,
      },
      {
        date: '2024-03-13',
        name: 'Wed',
        dayIndex: 3,
        day: 13,
      },
      {
        date: '2024-03-14',
        name: 'Thu',
        dayIndex: 4,
        day: 14,
      },
      {
        date: '2024-03-15',
        name: 'Fri',
        dayIndex: 5,
        day: 15,
      },
      {
        date: '2024-03-16',
        name: 'Sat',
        dayIndex: 6,
        day: 16,
      },
      {
        date: '2024-03-17',
        name: 'Sun',
        dayIndex: 0,
        day: 17,
      },
      {
        date: '2024-03-18',
        name: 'Mon',
        dayIndex: 1,
        day: 18,
      },
      {
        date: '2024-03-19',
        name: 'Tue',
        dayIndex: 2,
        day: 19,
      },
      {
        date: '2024-03-20',
        name: 'Wed',
        dayIndex: 3,
        day: 20,
      },
      {
        date: '2024-03-21',
        name: 'Thu',
        dayIndex: 4,
        day: 21,
      },
      {
        date: '2024-03-22',
        name: 'Fri',
        dayIndex: 5,
        day: 22,
      },
      {
        date: '2024-03-23',
        name: 'Sat',
        dayIndex: 6,
        day: 23,
      },
      {
        date: '2024-03-24',
        name: 'Sun',
        dayIndex: 0,
        day: 24,
      },
      {
        date: '2024-03-25',
        name: 'Mon',
        dayIndex: 1,
        day: 25,
      },
      {
        date: '2024-03-26',
        name: 'Tue',
        dayIndex: 2,
        day: 26,
      },
      {
        date: '2024-03-27',
        name: 'Wed',
        dayIndex: 3,
        day: 27,
      },
      {
        date: '2024-03-28',
        name: 'Thu',
        dayIndex: 4,
        day: 28,
      },
      {
        date: '2024-03-29',
        name: 'Fri',
        dayIndex: 5,
        day: 29,
      },
      {
        date: '2024-03-30',
        name: 'Sat',
        dayIndex: 6,
        day: 30,
      },
      {
        date: '2024-03-31',
        name: 'Sun',
        dayIndex: 0,
        day: 31,
      },
    ],
    offset: 5,
  },
  {
    year: 2024,
    monthIndex: 3,
    name: 'April',
    days: [
      {
        date: '2024-04-01',
        name: 'Mon',
        dayIndex: 1,
        day: 1,
      },
      {
        date: '2024-04-02',
        name: 'Tue',
        dayIndex: 2,
        day: 2,
      },
      {
        date: '2024-04-03',
        name: 'Wed',
        dayIndex: 3,
        day: 3,
      },
      {
        date: '2024-04-04',
        name: 'Thu',
        dayIndex: 4,
        day: 4,
      },
      {
        date: '2024-04-05',
        name: 'Fri',
        dayIndex: 5,
        day: 5,
      },
      {
        date: '2024-04-06',
        name: 'Sat',
        dayIndex: 6,
        day: 6,
      },
      {
        date: '2024-04-07',
        name: 'Sun',
        dayIndex: 0,
        day: 7,
      },
      {
        date: '2024-04-08',
        name: 'Mon',
        dayIndex: 1,
        day: 8,
      },
      {
        date: '2024-04-09',
        name: 'Tue',
        dayIndex: 2,
        day: 9,
      },
      {
        date: '2024-04-10',
        name: 'Wed',
        dayIndex: 3,
        day: 10,
      },
      {
        date: '2024-04-11',
        name: 'Thu',
        dayIndex: 4,
        day: 11,
      },
      {
        date: '2024-04-12',
        name: 'Fri',
        dayIndex: 5,
        day: 12,
      },
      {
        date: '2024-04-13',
        name: 'Sat',
        dayIndex: 6,
        day: 13,
      },
      {
        date: '2024-04-14',
        name: 'Sun',
        dayIndex: 0,
        day: 14,
      },
      {
        date: '2024-04-15',
        name: 'Mon',
        dayIndex: 1,
        day: 15,
      },
      {
        date: '2024-04-16',
        name: 'Tue',
        dayIndex: 2,
        day: 16,
      },
      {
        date: '2024-04-17',
        name: 'Wed',
        dayIndex: 3,
        day: 17,
      },
      {
        date: '2024-04-18',
        name: 'Thu',
        dayIndex: 4,
        day: 18,
      },
      {
        date: '2024-04-19',
        name: 'Fri',
        dayIndex: 5,
        day: 19,
      },
      {
        date: '2024-04-20',
        name: 'Sat',
        dayIndex: 6,
        day: 20,
      },
      {
        date: '2024-04-21',
        name: 'Sun',
        dayIndex: 0,
        day: 21,
      },
      {
        date: '2024-04-22',
        name: 'Mon',
        dayIndex: 1,
        day: 22,
      },
      {
        date: '2024-04-23',
        name: 'Tue',
        dayIndex: 2,
        day: 23,
      },
      {
        date: '2024-04-24',
        name: 'Wed',
        dayIndex: 3,
        day: 24,
      },
      {
        date: '2024-04-25',
        name: 'Thu',
        dayIndex: 4,
        day: 25,
      },
      {
        date: '2024-04-26',
        name: 'Fri',
        dayIndex: 5,
        day: 26,
      },
      {
        date: '2024-04-27',
        name: 'Sat',
        dayIndex: 6,
        day: 27,
      },
      {
        date: '2024-04-28',
        name: 'Sun',
        dayIndex: 0,
        day: 28,
      },
      {
        date: '2024-04-29',
        name: 'Mon',
        dayIndex: 1,
        day: 29,
      },
      {
        date: '2024-04-30',
        name: 'Tue',
        dayIndex: 2,
        day: 30,
      },
    ],
    offset: 1,
  },
  {
    year: 2024,
    monthIndex: 4,
    name: 'May',
    days: [
      {
        date: '2024-05-01',
        name: 'Wed',
        dayIndex: 3,
        day: 1,
      },
      {
        date: '2024-05-02',
        name: 'Thu',
        dayIndex: 4,
        day: 2,
      },
      {
        date: '2024-05-03',
        name: 'Fri',
        dayIndex: 5,
        day: 3,
      },
      {
        date: '2024-05-04',
        name: 'Sat',
        dayIndex: 6,
        day: 4,
      },
      {
        date: '2024-05-05',
        name: 'Sun',
        dayIndex: 0,
        day: 5,
      },
      {
        date: '2024-05-06',
        name: 'Mon',
        dayIndex: 1,
        day: 6,
      },
      {
        date: '2024-05-07',
        name: 'Tue',
        dayIndex: 2,
        day: 7,
      },
      {
        date: '2024-05-08',
        name: 'Wed',
        dayIndex: 3,
        day: 8,
      },
      {
        date: '2024-05-09',
        name: 'Thu',
        dayIndex: 4,
        day: 9,
      },
      {
        date: '2024-05-10',
        name: 'Fri',
        dayIndex: 5,
        day: 10,
      },
      {
        date: '2024-05-11',
        name: 'Sat',
        dayIndex: 6,
        day: 11,
      },
      {
        date: '2024-05-12',
        name: 'Sun',
        dayIndex: 0,
        day: 12,
      },
      {
        date: '2024-05-13',
        name: 'Mon',
        dayIndex: 1,
        day: 13,
      },
      {
        date: '2024-05-14',
        name: 'Tue',
        dayIndex: 2,
        day: 14,
      },
      {
        date: '2024-05-15',
        name: 'Wed',
        dayIndex: 3,
        day: 15,
      },
      {
        date: '2024-05-16',
        name: 'Thu',
        dayIndex: 4,
        day: 16,
      },
      {
        date: '2024-05-17',
        name: 'Fri',
        dayIndex: 5,
        day: 17,
      },
      {
        date: '2024-05-18',
        name: 'Sat',
        dayIndex: 6,
        day: 18,
      },
      {
        date: '2024-05-19',
        name: 'Sun',
        dayIndex: 0,
        day: 19,
      },
      {
        date: '2024-05-20',
        name: 'Mon',
        dayIndex: 1,
        day: 20,
      },
      {
        date: '2024-05-21',
        name: 'Tue',
        dayIndex: 2,
        day: 21,
      },
      {
        date: '2024-05-22',
        name: 'Wed',
        dayIndex: 3,
        day: 22,
      },
      {
        date: '2024-05-23',
        name: 'Thu',
        dayIndex: 4,
        day: 23,
      },
      {
        date: '2024-05-24',
        name: 'Fri',
        dayIndex: 5,
        day: 24,
      },
      {
        date: '2024-05-25',
        name: 'Sat',
        dayIndex: 6,
        day: 25,
      },
      {
        date: '2024-05-26',
        name: 'Sun',
        dayIndex: 0,
        day: 26,
      },
      {
        date: '2024-05-27',
        name: 'Mon',
        dayIndex: 1,
        day: 27,
      },
      {
        date: '2024-05-28',
        name: 'Tue',
        dayIndex: 2,
        day: 28,
      },
      {
        date: '2024-05-29',
        name: 'Wed',
        dayIndex: 3,
        day: 29,
      },
      {
        date: '2024-05-30',
        name: 'Thu',
        dayIndex: 4,
        day: 30,
      },
      {
        date: '2024-05-31',
        name: 'Fri',
        dayIndex: 5,
        day: 31,
      },
    ],
    offset: 3,
  },
  {
    year: 2024,
    monthIndex: 5,
    name: 'June',
    days: [
      {
        date: '2024-06-01',
        name: 'Sat',
        dayIndex: 6,
        day: 1,
      },
      {
        date: '2024-06-02',
        name: 'Sun',
        dayIndex: 0,
        day: 2,
      },
      {
        date: '2024-06-03',
        name: 'Mon',
        dayIndex: 1,
        day: 3,
      },
      {
        date: '2024-06-04',
        name: 'Tue',
        dayIndex: 2,
        day: 4,
      },
      {
        date: '2024-06-05',
        name: 'Wed',
        dayIndex: 3,
        day: 5,
      },
      {
        date: '2024-06-06',
        name: 'Thu',
        dayIndex: 4,
        day: 6,
      },
      {
        date: '2024-06-07',
        name: 'Fri',
        dayIndex: 5,
        day: 7,
      },
      {
        date: '2024-06-08',
        name: 'Sat',
        dayIndex: 6,
        day: 8,
      },
      {
        date: '2024-06-09',
        name: 'Sun',
        dayIndex: 0,
        day: 9,
      },
      {
        date: '2024-06-10',
        name: 'Mon',
        dayIndex: 1,
        day: 10,
      },
      {
        date: '2024-06-11',
        name: 'Tue',
        dayIndex: 2,
        day: 11,
      },
      {
        date: '2024-06-12',
        name: 'Wed',
        dayIndex: 3,
        day: 12,
      },
      {
        date: '2024-06-13',
        name: 'Thu',
        dayIndex: 4,
        day: 13,
      },
      {
        date: '2024-06-14',
        name: 'Fri',
        dayIndex: 5,
        day: 14,
      },
      {
        date: '2024-06-15',
        name: 'Sat',
        dayIndex: 6,
        day: 15,
      },
      {
        date: '2024-06-16',
        name: 'Sun',
        dayIndex: 0,
        day: 16,
      },
      {
        date: '2024-06-17',
        name: 'Mon',
        dayIndex: 1,
        day: 17,
      },
      {
        date: '2024-06-18',
        name: 'Tue',
        dayIndex: 2,
        day: 18,
      },
      {
        date: '2024-06-19',
        name: 'Wed',
        dayIndex: 3,
        day: 19,
      },
      {
        date: '2024-06-20',
        name: 'Thu',
        dayIndex: 4,
        day: 20,
      },
      {
        date: '2024-06-21',
        name: 'Fri',
        dayIndex: 5,
        day: 21,
      },
      {
        date: '2024-06-22',
        name: 'Sat',
        dayIndex: 6,
        day: 22,
      },
      {
        date: '2024-06-23',
        name: 'Sun',
        dayIndex: 0,
        day: 23,
      },
      {
        date: '2024-06-24',
        name: 'Mon',
        dayIndex: 1,
        day: 24,
      },
      {
        date: '2024-06-25',
        name: 'Tue',
        dayIndex: 2,
        day: 25,
      },
      {
        date: '2024-06-26',
        name: 'Wed',
        dayIndex: 3,
        day: 26,
      },
      {
        date: '2024-06-27',
        name: 'Thu',
        dayIndex: 4,
        day: 27,
      },
      {
        date: '2024-06-28',
        name: 'Fri',
        dayIndex: 5,
        day: 28,
      },
      {
        date: '2024-06-29',
        name: 'Sat',
        dayIndex: 6,
        day: 29,
      },
      {
        date: '2024-06-30',
        name: 'Sun',
        dayIndex: 0,
        day: 30,
      },
    ],
    offset: 6,
  },
  {
    year: 2024,
    monthIndex: 6,
    name: 'July',
    days: [
      {
        date: '2024-07-01',
        name: 'Mon',
        dayIndex: 1,
        day: 1,
      },
      {
        date: '2024-07-02',
        name: 'Tue',
        dayIndex: 2,
        day: 2,
      },
      {
        date: '2024-07-03',
        name: 'Wed',
        dayIndex: 3,
        day: 3,
      },
      {
        date: '2024-07-04',
        name: 'Thu',
        dayIndex: 4,
        day: 4,
      },
      {
        date: '2024-07-05',
        name: 'Fri',
        dayIndex: 5,
        day: 5,
      },
      {
        date: '2024-07-06',
        name: 'Sat',
        dayIndex: 6,
        day: 6,
      },
      {
        date: '2024-07-07',
        name: 'Sun',
        dayIndex: 0,
        day: 7,
      },
      {
        date: '2024-07-08',
        name: 'Mon',
        dayIndex: 1,
        day: 8,
      },
      {
        date: '2024-07-09',
        name: 'Tue',
        dayIndex: 2,
        day: 9,
      },
      {
        date: '2024-07-10',
        name: 'Wed',
        dayIndex: 3,
        day: 10,
      },
      {
        date: '2024-07-11',
        name: 'Thu',
        dayIndex: 4,
        day: 11,
      },
      {
        date: '2024-07-12',
        name: 'Fri',
        dayIndex: 5,
        day: 12,
      },
      {
        date: '2024-07-13',
        name: 'Sat',
        dayIndex: 6,
        day: 13,
      },
      {
        date: '2024-07-14',
        name: 'Sun',
        dayIndex: 0,
        day: 14,
      },
      {
        date: '2024-07-15',
        name: 'Mon',
        dayIndex: 1,
        day: 15,
      },
      {
        date: '2024-07-16',
        name: 'Tue',
        dayIndex: 2,
        day: 16,
      },
      {
        date: '2024-07-17',
        name: 'Wed',
        dayIndex: 3,
        day: 17,
      },
      {
        date: '2024-07-18',
        name: 'Thu',
        dayIndex: 4,
        day: 18,
      },
      {
        date: '2024-07-19',
        name: 'Fri',
        dayIndex: 5,
        day: 19,
      },
      {
        date: '2024-07-20',
        name: 'Sat',
        dayIndex: 6,
        day: 20,
      },
      {
        date: '2024-07-21',
        name: 'Sun',
        dayIndex: 0,
        day: 21,
      },
      {
        date: '2024-07-22',
        name: 'Mon',
        dayIndex: 1,
        day: 22,
      },
      {
        date: '2024-07-23',
        name: 'Tue',
        dayIndex: 2,
        day: 23,
      },
      {
        date: '2024-07-24',
        name: 'Wed',
        dayIndex: 3,
        day: 24,
      },
      {
        date: '2024-07-25',
        name: 'Thu',
        dayIndex: 4,
        day: 25,
      },
      {
        date: '2024-07-26',
        name: 'Fri',
        dayIndex: 5,
        day: 26,
      },
      {
        date: '2024-07-27',
        name: 'Sat',
        dayIndex: 6,
        day: 27,
      },
      {
        date: '2024-07-28',
        name: 'Sun',
        dayIndex: 0,
        day: 28,
      },
      {
        date: '2024-07-29',
        name: 'Mon',
        dayIndex: 1,
        day: 29,
      },
      {
        date: '2024-07-30',
        name: 'Tue',
        dayIndex: 2,
        day: 30,
      },
      {
        date: '2024-07-31',
        name: 'Wed',
        dayIndex: 3,
        day: 31,
      },
    ],
    offset: 1,
  },
  {
    year: 2024,
    monthIndex: 7,
    name: 'August',
    days: [
      {
        date: '2024-08-01',
        name: 'Thu',
        dayIndex: 4,
        day: 1,
      },
      {
        date: '2024-08-02',
        name: 'Fri',
        dayIndex: 5,
        day: 2,
      },
      {
        date: '2024-08-03',
        name: 'Sat',
        dayIndex: 6,
        day: 3,
      },
      {
        date: '2024-08-04',
        name: 'Sun',
        dayIndex: 0,
        day: 4,
      },
      {
        date: '2024-08-05',
        name: 'Mon',
        dayIndex: 1,
        day: 5,
      },
      {
        date: '2024-08-06',
        name: 'Tue',
        dayIndex: 2,
        day: 6,
      },
      {
        date: '2024-08-07',
        name: 'Wed',
        dayIndex: 3,
        day: 7,
      },
      {
        date: '2024-08-08',
        name: 'Thu',
        dayIndex: 4,
        day: 8,
      },
      {
        date: '2024-08-09',
        name: 'Fri',
        dayIndex: 5,
        day: 9,
      },
      {
        date: '2024-08-10',
        name: 'Sat',
        dayIndex: 6,
        day: 10,
      },
      {
        date: '2024-08-11',
        name: 'Sun',
        dayIndex: 0,
        day: 11,
      },
      {
        date: '2024-08-12',
        name: 'Mon',
        dayIndex: 1,
        day: 12,
      },
      {
        date: '2024-08-13',
        name: 'Tue',
        dayIndex: 2,
        day: 13,
      },
      {
        date: '2024-08-14',
        name: 'Wed',
        dayIndex: 3,
        day: 14,
      },
      {
        date: '2024-08-15',
        name: 'Thu',
        dayIndex: 4,
        day: 15,
      },
      {
        date: '2024-08-16',
        name: 'Fri',
        dayIndex: 5,
        day: 16,
      },
      {
        date: '2024-08-17',
        name: 'Sat',
        dayIndex: 6,
        day: 17,
      },
      {
        date: '2024-08-18',
        name: 'Sun',
        dayIndex: 0,
        day: 18,
      },
      {
        date: '2024-08-19',
        name: 'Mon',
        dayIndex: 1,
        day: 19,
      },
      {
        date: '2024-08-20',
        name: 'Tue',
        dayIndex: 2,
        day: 20,
      },
      {
        date: '2024-08-21',
        name: 'Wed',
        dayIndex: 3,
        day: 21,
      },
      {
        date: '2024-08-22',
        name: 'Thu',
        dayIndex: 4,
        day: 22,
      },
      {
        date: '2024-08-23',
        name: 'Fri',
        dayIndex: 5,
        day: 23,
      },
      {
        date: '2024-08-24',
        name: 'Sat',
        dayIndex: 6,
        day: 24,
      },
      {
        date: '2024-08-25',
        name: 'Sun',
        dayIndex: 0,
        day: 25,
      },
      {
        date: '2024-08-26',
        name: 'Mon',
        dayIndex: 1,
        day: 26,
      },
      {
        date: '2024-08-27',
        name: 'Tue',
        dayIndex: 2,
        day: 27,
      },
      {
        date: '2024-08-28',
        name: 'Wed',
        dayIndex: 3,
        day: 28,
      },
      {
        date: '2024-08-29',
        name: 'Thu',
        dayIndex: 4,
        day: 29,
      },
      {
        date: '2024-08-30',
        name: 'Fri',
        dayIndex: 5,
        day: 30,
      },
      {
        date: '2024-08-31',
        name: 'Sat',
        dayIndex: 6,
        day: 31,
      },
    ],
    offset: 4,
  },
  {
    year: 2024,
    monthIndex: 8,
    name: 'September',
    days: [
      {
        date: '2024-09-01',
        name: 'Sun',
        dayIndex: 0,
        day: 1,
      },
      {
        date: '2024-09-02',
        name: 'Mon',
        dayIndex: 1,
        day: 2,
      },
      {
        date: '2024-09-03',
        name: 'Tue',
        dayIndex: 2,
        day: 3,
      },
      {
        date: '2024-09-04',
        name: 'Wed',
        dayIndex: 3,
        day: 4,
      },
      {
        date: '2024-09-05',
        name: 'Thu',
        dayIndex: 4,
        day: 5,
      },
      {
        date: '2024-09-06',
        name: 'Fri',
        dayIndex: 5,
        day: 6,
      },
      {
        date: '2024-09-07',
        name: 'Sat',
        dayIndex: 6,
        day: 7,
      },
      {
        date: '2024-09-08',
        name: 'Sun',
        dayIndex: 0,
        day: 8,
      },
      {
        date: '2024-09-09',
        name: 'Mon',
        dayIndex: 1,
        day: 9,
      },
      {
        date: '2024-09-10',
        name: 'Tue',
        dayIndex: 2,
        day: 10,
      },
      {
        date: '2024-09-11',
        name: 'Wed',
        dayIndex: 3,
        day: 11,
      },
      {
        date: '2024-09-12',
        name: 'Thu',
        dayIndex: 4,
        day: 12,
      },
      {
        date: '2024-09-13',
        name: 'Fri',
        dayIndex: 5,
        day: 13,
      },
      {
        date: '2024-09-14',
        name: 'Sat',
        dayIndex: 6,
        day: 14,
      },
      {
        date: '2024-09-15',
        name: 'Sun',
        dayIndex: 0,
        day: 15,
      },
      {
        date: '2024-09-16',
        name: 'Mon',
        dayIndex: 1,
        day: 16,
      },
      {
        date: '2024-09-17',
        name: 'Tue',
        dayIndex: 2,
        day: 17,
      },
      {
        date: '2024-09-18',
        name: 'Wed',
        dayIndex: 3,
        day: 18,
      },
      {
        date: '2024-09-19',
        name: 'Thu',
        dayIndex: 4,
        day: 19,
      },
      {
        date: '2024-09-20',
        name: 'Fri',
        dayIndex: 5,
        day: 20,
      },
      {
        date: '2024-09-21',
        name: 'Sat',
        dayIndex: 6,
        day: 21,
      },
      {
        date: '2024-09-22',
        name: 'Sun',
        dayIndex: 0,
        day: 22,
      },
      {
        date: '2024-09-23',
        name: 'Mon',
        dayIndex: 1,
        day: 23,
      },
      {
        date: '2024-09-24',
        name: 'Tue',
        dayIndex: 2,
        day: 24,
      },
      {
        date: '2024-09-25',
        name: 'Wed',
        dayIndex: 3,
        day: 25,
      },
      {
        date: '2024-09-26',
        name: 'Thu',
        dayIndex: 4,
        day: 26,
      },
      {
        date: '2024-09-27',
        name: 'Fri',
        dayIndex: 5,
        day: 27,
      },
      {
        date: '2024-09-28',
        name: 'Sat',
        dayIndex: 6,
        day: 28,
      },
      {
        date: '2024-09-29',
        name: 'Sun',
        dayIndex: 0,
        day: 29,
      },
      {
        date: '2024-09-30',
        name: 'Mon',
        dayIndex: 1,
        day: 30,
      },
    ],
    offset: 0,
  },
  {
    year: 2024,
    monthIndex: 9,
    name: 'October',
    days: [
      {
        date: '2024-10-01',
        name: 'Tue',
        dayIndex: 2,
        day: 1,
      },
      {
        date: '2024-10-02',
        name: 'Wed',
        dayIndex: 3,
        day: 2,
      },
      {
        date: '2024-10-03',
        name: 'Thu',
        dayIndex: 4,
        day: 3,
      },
      {
        date: '2024-10-04',
        name: 'Fri',
        dayIndex: 5,
        day: 4,
      },
      {
        date: '2024-10-05',
        name: 'Sat',
        dayIndex: 6,
        day: 5,
      },
      {
        date: '2024-10-06',
        name: 'Sun',
        dayIndex: 0,
        day: 6,
      },
      {
        date: '2024-10-07',
        name: 'Mon',
        dayIndex: 1,
        day: 7,
      },
      {
        date: '2024-10-08',
        name: 'Tue',
        dayIndex: 2,
        day: 8,
      },
      {
        date: '2024-10-09',
        name: 'Wed',
        dayIndex: 3,
        day: 9,
      },
      {
        date: '2024-10-10',
        name: 'Thu',
        dayIndex: 4,
        day: 10,
      },
      {
        date: '2024-10-11',
        name: 'Fri',
        dayIndex: 5,
        day: 11,
      },
      {
        date: '2024-10-12',
        name: 'Sat',
        dayIndex: 6,
        day: 12,
      },
      {
        date: '2024-10-13',
        name: 'Sun',
        dayIndex: 0,
        day: 13,
      },
      {
        date: '2024-10-14',
        name: 'Mon',
        dayIndex: 1,
        day: 14,
      },
      {
        date: '2024-10-15',
        name: 'Tue',
        dayIndex: 2,
        day: 15,
      },
      {
        date: '2024-10-16',
        name: 'Wed',
        dayIndex: 3,
        day: 16,
      },
      {
        date: '2024-10-17',
        name: 'Thu',
        dayIndex: 4,
        day: 17,
      },
      {
        date: '2024-10-18',
        name: 'Fri',
        dayIndex: 5,
        day: 18,
      },
      {
        date: '2024-10-19',
        name: 'Sat',
        dayIndex: 6,
        day: 19,
      },
      {
        date: '2024-10-20',
        name: 'Sun',
        dayIndex: 0,
        day: 20,
      },
      {
        date: '2024-10-21',
        name: 'Mon',
        dayIndex: 1,
        day: 21,
      },
      {
        date: '2024-10-22',
        name: 'Tue',
        dayIndex: 2,
        day: 22,
      },
      {
        date: '2024-10-23',
        name: 'Wed',
        dayIndex: 3,
        day: 23,
      },
      {
        date: '2024-10-24',
        name: 'Thu',
        dayIndex: 4,
        day: 24,
      },
      {
        date: '2024-10-25',
        name: 'Fri',
        dayIndex: 5,
        day: 25,
      },
      {
        date: '2024-10-26',
        name: 'Sat',
        dayIndex: 6,
        day: 26,
      },
      {
        date: '2024-10-27',
        name: 'Sun',
        dayIndex: 0,
        day: 27,
      },
      {
        date: '2024-10-28',
        name: 'Mon',
        dayIndex: 1,
        day: 28,
      },
      {
        date: '2024-10-29',
        name: 'Tue',
        dayIndex: 2,
        day: 29,
      },
      {
        date: '2024-10-30',
        name: 'Wed',
        dayIndex: 3,
        day: 30,
      },
      {
        date: '2024-10-31',
        name: 'Thu',
        dayIndex: 4,
        day: 31,
      },
    ],
    offset: 2,
  },
  {
    year: 2024,
    monthIndex: 10,
    name: 'November',
    days: [
      {
        date: '2024-11-01',
        name: 'Fri',
        dayIndex: 5,
        day: 1,
      },
      {
        date: '2024-11-02',
        name: 'Sat',
        dayIndex: 6,
        day: 2,
      },
      {
        date: '2024-11-03',
        name: 'Sun',
        dayIndex: 0,
        day: 3,
      },
      {
        date: '2024-11-04',
        name: 'Mon',
        dayIndex: 1,
        day: 4,
      },
      {
        date: '2024-11-05',
        name: 'Tue',
        dayIndex: 2,
        day: 5,
      },
      {
        date: '2024-11-06',
        name: 'Wed',
        dayIndex: 3,
        day: 6,
      },
      {
        date: '2024-11-07',
        name: 'Thu',
        dayIndex: 4,
        day: 7,
      },
      {
        date: '2024-11-08',
        name: 'Fri',
        dayIndex: 5,
        day: 8,
      },
      {
        date: '2024-11-09',
        name: 'Sat',
        dayIndex: 6,
        day: 9,
      },
      {
        date: '2024-11-10',
        name: 'Sun',
        dayIndex: 0,
        day: 10,
      },
      {
        date: '2024-11-11',
        name: 'Mon',
        dayIndex: 1,
        day: 11,
      },
      {
        date: '2024-11-12',
        name: 'Tue',
        dayIndex: 2,
        day: 12,
      },
      {
        date: '2024-11-13',
        name: 'Wed',
        dayIndex: 3,
        day: 13,
      },
      {
        date: '2024-11-14',
        name: 'Thu',
        dayIndex: 4,
        day: 14,
      },
      {
        date: '2024-11-15',
        name: 'Fri',
        dayIndex: 5,
        day: 15,
      },
      {
        date: '2024-11-16',
        name: 'Sat',
        dayIndex: 6,
        day: 16,
      },
      {
        date: '2024-11-17',
        name: 'Sun',
        dayIndex: 0,
        day: 17,
      },
      {
        date: '2024-11-18',
        name: 'Mon',
        dayIndex: 1,
        day: 18,
      },
      {
        date: '2024-11-19',
        name: 'Tue',
        dayIndex: 2,
        day: 19,
      },
      {
        date: '2024-11-20',
        name: 'Wed',
        dayIndex: 3,
        day: 20,
      },
      {
        date: '2024-11-21',
        name: 'Thu',
        dayIndex: 4,
        day: 21,
      },
      {
        date: '2024-11-22',
        name: 'Fri',
        dayIndex: 5,
        day: 22,
      },
      {
        date: '2024-11-23',
        name: 'Sat',
        dayIndex: 6,
        day: 23,
      },
      {
        date: '2024-11-24',
        name: 'Sun',
        dayIndex: 0,
        day: 24,
      },
      {
        date: '2024-11-25',
        name: 'Mon',
        dayIndex: 1,
        day: 25,
      },
      {
        date: '2024-11-26',
        name: 'Tue',
        dayIndex: 2,
        day: 26,
      },
      {
        date: '2024-11-27',
        name: 'Wed',
        dayIndex: 3,
        day: 27,
      },
      {
        date: '2024-11-28',
        name: 'Thu',
        dayIndex: 4,
        day: 28,
      },
      {
        date: '2024-11-29',
        name: 'Fri',
        dayIndex: 5,
        day: 29,
      },
      {
        date: '2024-11-30',
        name: 'Sat',
        dayIndex: 6,
        day: 30,
      },
    ],
    offset: 5,
  },
  {
    year: 2024,
    monthIndex: 11,
    name: 'December',
    days: [
      {
        date: '2024-12-01',
        name: 'Sun',
        dayIndex: 0,
        day: 1,
      },
      {
        date: '2024-12-02',
        name: 'Mon',
        dayIndex: 1,
        day: 2,
      },
      {
        date: '2024-12-03',
        name: 'Tue',
        dayIndex: 2,
        day: 3,
      },
      {
        date: '2024-12-04',
        name: 'Wed',
        dayIndex: 3,
        day: 4,
      },
      {
        date: '2024-12-05',
        name: 'Thu',
        dayIndex: 4,
        day: 5,
      },
      {
        date: '2024-12-06',
        name: 'Fri',
        dayIndex: 5,
        day: 6,
      },
      {
        date: '2024-12-07',
        name: 'Sat',
        dayIndex: 6,
        day: 7,
      },
      {
        date: '2024-12-08',
        name: 'Sun',
        dayIndex: 0,
        day: 8,
      },
      {
        date: '2024-12-09',
        name: 'Mon',
        dayIndex: 1,
        day: 9,
      },
      {
        date: '2024-12-10',
        name: 'Tue',
        dayIndex: 2,
        day: 10,
      },
      {
        date: '2024-12-11',
        name: 'Wed',
        dayIndex: 3,
        day: 11,
      },
      {
        date: '2024-12-12',
        name: 'Thu',
        dayIndex: 4,
        day: 12,
      },
      {
        date: '2024-12-13',
        name: 'Fri',
        dayIndex: 5,
        day: 13,
      },
      {
        date: '2024-12-14',
        name: 'Sat',
        dayIndex: 6,
        day: 14,
      },
      {
        date: '2024-12-15',
        name: 'Sun',
        dayIndex: 0,
        day: 15,
      },
      {
        date: '2024-12-16',
        name: 'Mon',
        dayIndex: 1,
        day: 16,
      },
      {
        date: '2024-12-17',
        name: 'Tue',
        dayIndex: 2,
        day: 17,
      },
      {
        date: '2024-12-18',
        name: 'Wed',
        dayIndex: 3,
        day: 18,
      },
      {
        date: '2024-12-19',
        name: 'Thu',
        dayIndex: 4,
        day: 19,
      },
      {
        date: '2024-12-20',
        name: 'Fri',
        dayIndex: 5,
        day: 20,
      },
      {
        date: '2024-12-21',
        name: 'Sat',
        dayIndex: 6,
        day: 21,
      },
      {
        date: '2024-12-22',
        name: 'Sun',
        dayIndex: 0,
        day: 22,
      },
      {
        date: '2024-12-23',
        name: 'Mon',
        dayIndex: 1,
        day: 23,
      },
      {
        date: '2024-12-24',
        name: 'Tue',
        dayIndex: 2,
        day: 24,
      },
      {
        date: '2024-12-25',
        name: 'Wed',
        dayIndex: 3,
        day: 25,
      },
      {
        date: '2024-12-26',
        name: 'Thu',
        dayIndex: 4,
        day: 26,
      },
      {
        date: '2024-12-27',
        name: 'Fri',
        dayIndex: 5,
        day: 27,
      },
      {
        date: '2024-12-28',
        name: 'Sat',
        dayIndex: 6,
        day: 28,
      },
      {
        date: '2024-12-29',
        name: 'Sun',
        dayIndex: 0,
        day: 29,
      },
      {
        date: '2024-12-30',
        name: 'Mon',
        dayIndex: 1,
        day: 30,
      },
      {
        date: '2024-12-31',
        name: 'Tue',
        dayIndex: 2,
        day: 31,
      },
    ],
    offset: 0,
  },
]
